[2025-10-04T23:17:16.623+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_data_dag.ingest_tickets_data manual__2025-10-04T23:06:49.926285+00:00 [queued]>
[2025-10-04T23:17:16.641+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_data_dag.ingest_tickets_data manual__2025-10-04T23:06:49.926285+00:00 [queued]>
[2025-10-04T23:17:16.642+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-10-04T23:17:16.669+0000] {taskinstance.py:2191} INFO - Executing <Task(S3ToSqlOperator): ingest_tickets_data> on 2025-10-04 23:06:49.926285+00:00
[2025-10-04T23:17:16.679+0000] {standard_task_runner.py:60} INFO - Started process 1977 to run task
[2025-10-04T23:17:16.686+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_dag', 'ingest_tickets_data', 'manual__2025-10-04T23:06:49.926285+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/dag_ingest_data.py', '--cfg-path', '/tmp/tmpee20kod9']
[2025-10-04T23:17:16.692+0000] {standard_task_runner.py:88} INFO - Job 8: Subtask ingest_tickets_data
[2025-10-04T23:17:16.808+0000] {task_command.py:423} INFO - Running <TaskInstance: ingest_data_dag.ingest_tickets_data manual__2025-10-04T23:06:49.926285+00:00 [running]> on host ff034d7c1964
[2025-10-04T23:17:16.930+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_data_dag' AIRFLOW_CTX_TASK_ID='ingest_tickets_data' AIRFLOW_CTX_EXECUTION_DATE='2025-10-04T23:06:49.926285+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-04T23:06:49.926285+00:00'
[2025-10-04T23:17:16.932+0000] {s3_to_sql.py:105} INFO - Loading support_tickets.csv to SQL table "staging"."tickets"...
[2025-10-04T23:17:16.947+0000] {base.py:83} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-04T23:17:16.949+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-10-04T23:17:17.456+0000] {base.py:83} INFO - Using connection ID 'postgres_warehouse' for task execution.
[2025-10-04T23:17:17.462+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/transfers/s3_to_sql.py", line 119, in execute
    rows=self.parser(local_tempfile.name),
TypeError: 'str' object is not callable
[2025-10-04T23:17:17.477+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=ingest_data_dag, task_id=ingest_tickets_data, execution_date=20251004T230649, start_date=20251004T231716, end_date=20251004T231717
[2025-10-04T23:17:17.495+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 8 for task ingest_tickets_data ('str' object is not callable; 1977)
[2025-10-04T23:17:17.544+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-10-04T23:17:17.579+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
