[2025-10-04T23:17:48.134+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_data_dag.ingest_orders_data manual__2025-10-04T23:17:44.635799+00:00 [queued]>
[2025-10-04T23:17:48.151+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_data_dag.ingest_orders_data manual__2025-10-04T23:17:44.635799+00:00 [queued]>
[2025-10-04T23:17:48.152+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-10-04T23:17:48.175+0000] {taskinstance.py:2191} INFO - Executing <Task(S3ToSqlOperator): ingest_orders_data> on 2025-10-04 23:17:44.635799+00:00
[2025-10-04T23:17:48.188+0000] {standard_task_runner.py:60} INFO - Started process 2007 to run task
[2025-10-04T23:17:48.202+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_dag', 'ingest_orders_data', 'manual__2025-10-04T23:17:44.635799+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/dag_ingest_data.py', '--cfg-path', '/tmp/tmp5n8wctzm']
[2025-10-04T23:17:48.211+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask ingest_orders_data
[2025-10-04T23:17:48.340+0000] {task_command.py:423} INFO - Running <TaskInstance: ingest_data_dag.ingest_orders_data manual__2025-10-04T23:17:44.635799+00:00 [running]> on host ff034d7c1964
[2025-10-04T23:17:48.503+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_data_dag' AIRFLOW_CTX_TASK_ID='ingest_orders_data' AIRFLOW_CTX_EXECUTION_DATE='2025-10-04T23:17:44.635799+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-04T23:17:44.635799+00:00'
[2025-10-04T23:17:48.511+0000] {s3_to_sql.py:105} INFO - Loading orders.csv to SQL table "staging"."orders"...
[2025-10-04T23:17:48.535+0000] {base.py:83} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-04T23:17:48.538+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-10-04T23:17:49.214+0000] {base.py:83} INFO - Using connection ID 'postgres_warehouse' for task execution.
[2025-10-04T23:17:49.220+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/transfers/s3_to_sql.py", line 119, in execute
    rows=self.parser(local_tempfile.name),
TypeError: 'str' object is not callable
[2025-10-04T23:17:49.236+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=ingest_data_dag, task_id=ingest_orders_data, execution_date=20251004T231744, start_date=20251004T231748, end_date=20251004T231749
[2025-10-04T23:17:49.265+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 10 for task ingest_orders_data ('str' object is not callable; 2007)
[2025-10-04T23:17:49.337+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-10-04T23:17:49.382+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
